# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        ls -la /usr/share
        ls -la /usr/share/dotnet
   
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'
    

    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        ls -la /usr/share
        ls -la /usr/share/dotnet
