# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        wget https://storage.googleapis.com/gctf-h4ck-2022-attachments-project/cec5317acaa111092eef6da3df8e260dccd69ce8b17aa445a26a7a6771f972301ac3ff20108cf86aa868da1463e486347114e0456ba5b5ca2a3a399f69391e76
        ls
        unzip cec5317acaa111092eef6da3df8e260dccd69ce8b17aa445a26a7a6771f972301ac3ff20108cf86aa868da1463e486347114e0456ba5b5ca2a3a399f69391e76
        tar xzf challenge.tar.gz
        cat > key << EOF
        -----BEGIN -----
        Y2VjNTMxN2FjYWExMTEwOTJlZWY2ZGEzZGY4ZTI2MGRjY2Q2OWNlOGIxN2FhNDQ1
        YTI2YTdhNjc3MWY5NzIzMDFhYzNmZjIwMTA4Y2Y4NmFhODY4ZGExNDYzZTQ4NjM0
        NzExNGUwNDU2YmE1YjVjYTJhM2EzOTlmNjkzOTFlNzY=
        -----END -----
        EOF
        cat key
        ./wannacry -encrypted_file flag -key_file key
